resource_types:
- name: helloworld
  type: registry-image
  source:
    # set repo of your helloworld resource
    repository: nexus.cardinalhealth.net:8445/security/testimplicitget
    tag: 1.0.7
    ## or use my helloworld resource
    # repository: yoshiyuki/concourse-helloworld-resource

resources:
- name: helloworld
  type: helloworld

jobs:
- name: hello_world
  plan:
  - put: helloworld
- name: hello_world_no_implicit_get
  plan:
  - put: helloworld
    get_params: { skip_download: true }
