#!/bin/bash


set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload="$(cat <&0)"

skip_download="$(jq -r '.params.skip_download // false' < $payload)"

if [ "$skip_download" = "false" ]; then
  echo '{ "version": { "ref": "none", "message": "Hello World" }, "metadata": [{ "name": "message", "value": "Hello World" }] }'
else
  echo '{ "version": { "ref": "none", "message": "Hello World no implicit" }, "metadata": [{ "name": "message", "value": "Hello World no implicit" }] }'
fi
